/* Generated by Yosys 0.9+4292 (git sha1 416efa19, clang 12.0.1 -fPIC -Os) */

module adder_gold(A, B, Cin, Sum, Cout);
  wire _0_;
  wire _1_;
  wire _2_;
  input A;
  input B;
  input Cin;
  output Cout;
  output Sum;
  NAND2 _3_ (
    .A(A),
    .B(Cin),
    .Q(_0_)
  );
  XOR2 _4_ (
    .A(A),
    .B(Cin),
    .Q(_1_)
  );
  NAND2 _5_ (
    .A(B),
    .B(_1_),
    .Q(_2_)
  );
  NAND2 _6_ (
    .A(_0_),
    .B(_2_),
    .Q(Cout)
  );
  XOR2 _7_ (
    .A(B),
    .B(_1_),
    .Q(Sum)
  );
endmodule
